image: Visual Studio 2019
configuration:
  - Debug
  - Release
platform:
  - Win32
install:
  - cd %APPVEYOR_BUILD_FOLDER%
  - git submodule update --init --recursive
build:
  project: PlymouthColdWar.sln
