// Generated by OP2Mapper 2.2.0
// at 11/25/2005 6:36:11 PM
// using template C:\Program Files\OP2Mapper\Default.tpl
// Total Number of Objects: 123
//#define WIN32_LEAN_AND_MEAN		// Exclude rarely-used stuff from Windows headers
//#include <windows.h>

#include <Outpost2DLL/Outpost2DLL.h>

void SetupObjects()
{
	// Create OP2Mapper generated objects
	// Note: this file has been edited from what it originally was.
	// I used the mapper to initially place everything, and then moved some things around
	// (ex. Lynxes) so they could go in groups or elsewhere.
	Unit x;
	TethysGame::CreateWallOrTube(37+31, 42-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(37+31, 43-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(37+31, 44-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(124+31, 55-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(124+31, 54-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(124+31, 53-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(123+31, 53-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(122+31, 53-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(121+31, 53-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(121+31, 52-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(121+31, 51-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(121+31, 50-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(121+31, 49-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(112+31, 46-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(111+31, 46-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 46-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 45-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 44-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 43-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 42-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 41-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 40-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 39-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 38-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 37-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 36-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 35-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 32-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(111+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(112+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(113+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(114+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(115+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(116+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(117+31, 33-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(117+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(118+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(119+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(120+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(121+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(122+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(123+31, 34-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(125+31, 36-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(125+31, 37-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(118+31, 35-1, 0, (map_id)17);
	TethysGame::CreateBeacon((map_id)81, 99+31, 19-1, 1, 1, -1);
	TethysGame::CreateWallOrTube(110+31, 29-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 30-1, 0, (map_id)17);
	TethysGame::CreateWallOrTube(110+31, 31-1, 0, (map_id)17);
	TethysGame::CreateBeacon((map_id)81, 87+31, 31-1, 0, 0, -1);
	TethysGame::CreateBeacon((map_id)81, 92+31, 53-1, 0, 1, -1);
	TethysGame::CreateWallOrTube(115+31, 48-1, 0, (map_id)17);
    TethysGame::CreateUnit(x, (map_id)28, LOCATION(34+31, 42-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)54, LOCATION(39+31, 46-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)9, LOCATION(39+31, 41-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)8, LOCATION(37+31, 41-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)1, LOCATION(41+31, 41-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)39, LOCATION(43+31, 47-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)58, LOCATION(31+31, 53-1), 0, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)5, LOCATION(38+31, 37-1), 0, (map_id)61, 0);
    TethysGame::CreateUnit(x, (map_id)5, LOCATION(41+31, 38-1), 0, (map_id)61, 0);
    TethysGame::CreateUnit(x, (map_id)5, LOCATION(44+31, 39-1), 0, (map_id)61, 0);
    TethysGame::CreateUnit(x, (map_id)5, LOCATION(45+31, 41-1), 0, (map_id)63, 0);
    TethysGame::CreateUnit(x, (map_id)58, LOCATION(87+31, 59-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)58, LOCATION(91+31, 59-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)58, LOCATION(87+31, 4-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)58, LOCATION(83+31, 4-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)58, LOCATION(91+31, 4-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)28, LOCATION(124+31, 60-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)39, LOCATION(124+31, 57-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)49, LOCATION(125+31, 34-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)50, LOCATION(125+31, 39-1), 1, (map_id)0, 0);
    TethysGame::CreateUnit(x, (map_id)23, LOCATION(117+31, 31-1), 1, (map_id)71, 0);
    TethysGame::CreateUnit(x, (map_id)23, LOCATION(118+31, 36-1), 1, (map_id)70, 0);
    TethysGame::CreateUnit(x, (map_id)23, LOCATION(106+31, 27-1), 1, (map_id)71, 0);
    TethysGame::CreateUnit(x, (map_id)23, LOCATION(98+31, 43-1), 1, (map_id)64, 0);


}
